import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

test("contains only the two gated invitation videos", async () => {
  const [page, layout, styles] = await Promise.all([
    readFile(new URL("../app/page.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/layout.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/globals.css", import.meta.url), "utf8"),
  ]);
  const source = `${page}\n${layout}\n${styles}`;

  assert.match(source, /\/first\.mp4/);
  assert.match(source, /\/secondv2\.mp4/);
  assert.match(source, /className=.*intro-video/i);
  assert.match(source, /aria-label="Open invitation"/i);
  assert.match(source, /OPEN INVITATION/);
  assert.match(source, /\.intro-action[\s\S]*background: transparent/);
  assert.match(source, /\.intro-action[\s\S]*color: transparent/);
  assert.match(source, /\.intro-action[\s\S]*box-shadow: none/);
  assert.match(source, /intro-sequence--locked/);
  assert.match(source, /overflow: hidden/);
  assert.doesNotMatch(source, /disabled={!isComplete}/);
  assert.match(source, /introStage === "first" \?/);
  assert.match(source, /setIntroStage\("second"\)/);
  assert.doesNotMatch(source, /scrollIntoView/);
  assert.match(source, /object-fit: cover/);
  assert.match(source, /intro-panel--full/);
  assert.match(source, /intro-video--full/);
  assert.match(source, /object-fit: contain/);
  assert.match(source, /aspect-ratio: 736 \/ 4088/);
  assert.match(source, /video\.addEventListener\("canplay", playIfVisible\)/);
  assert.match(source, /src="\/secondv2\.mp4"[\s\S]*autoPlay[\s\S]*preload="auto"/);
  assert.match(source, /poster="\/first-poster\.png"/);
  assert.match(source, /poster="\/secondv2-poster\.png"/);
  assert.match(source, /showAutoplayFallback/);
  assert.match(source, /video\.play\(\)[\s\S]*setShowAutoplayFallback\(true\)/);
  assert.match(source, /autoplay-poster/);
  assert.match(source, /countdown-panel/);
  assert.match(source, /url\("\/%20countdown\.png"\)/);
  assert.match(source, /164% 215%/);
  assert.match(source, /top: 53%/);
  assert.match(source, /--rsvp-countdown-height, 8%/);
  assert.match(source, /--rsvp-countdown-top, 90\.25%/);
  assert.match(source, /--rsvp-countdown-left, 11\.36%/);
  assert.match(source, /--rsvp-countdown-top/);
  assert.match(source, /transform: rotate\(var\(--rsvp-countdown-rotation, 0deg\)\)/);
  assert.match(source, /\.countdown-kicker[\s\S]*display: none/);
  assert.match(source, /\.countdown-grid span[\s\S]*display: none/);
  assert.match(source, /RSVPHotspots/);
  assert.match(source, /name="name"/);
  assert.match(source, /name="additionalInformation"/);
  assert.match(source, /name="attending" value="yes"/);
  assert.match(source, /name="attending" value="no"/);
  assert.match(source, /className="rsvp-submit-hotspot"/);
  assert.match(source, /aria-label="Submit RSVP"/);
  assert.match(source, /fetch\("\/api\/rsvp"/);
  assert.match(source, /background: rgba\(255, 212, 0, 0\.58\)/);
  assert.match(source, /rsvp-radio-hotspot--yes/);
  assert.match(source, /rsvp-radio-hotspot--no/);
  assert.match(source, /countdown to the ball/i);
  assert.match(source, /countdown-bloom/);
  assert.match(source, /countdown-bow/);
  assert.match(source, /repeating-linear-gradient/);
  assert.match(source, /Georgia, "Times New Roman", serif/);
  assert.match(source, /October 3 at 7 PM/);
  assert.match(source, /setInterval\(updateCountdown, 1000\)/);
  assert.match(source, /2026-10-03T19:00:00-04:00/);
  assert.match(source, /vinyl-record\.png/);
  assert.match(source, /fetchPriority="high"/);
  assert.match(source, /vinyl-spin 7s linear infinite/);
  assert.match(source, /vinyl-grow-in 800ms/);
  assert.match(source, /transform: translate\(-50%, -50%\) scale\(0\.18\)/);
  assert.match(source, /rotate\(360deg\)/);
  assert.match(source, /vinyl-record--paused/);
  assert.match(source, /animation-play-state: paused/);
  assert.match(source, /aria-label=\{vinylPaused \? "Play vinyl" : "Pause vinyl"\}/);
  assert.match(source, /Nicki Minaj - Moment 4 Life.*NickiMinajAtVEVO\.mp3/);
  assert.match(source, /song\.play\(\).*setVinylPaused\(false\)/);
  assert.match(source, /song\.pause\(\);[\s\S]*setVinylPaused\(true\)/);
  assert.match(source, /onVinylToggle=\{toggleVinylAndSong\}/);
  assert.match(source, /top: calc\(27\.5% - 22px\)/);
  assert.match(source, /left: 66\.5%/);
  assert.match(source, /id="details"/);
  assert.match(source, /--rsvp-name-top/);
  assert.match(source, /--rsvp-notes-top/);
  assert.match(source, /--rsvp-submit-top/);
  assert.match(source, /--rsvp-name-rotation/);
  assert.match(source, /--rsvp-submit-rotation/);
  assert.match(source, /--rsvp-name-background/);
  assert.match(source, /--rsvp-notes-background/);
  assert.match(source, /--rsvp-submit-background/);
  assert.match(source, /input:checked \+ span[\s\S]*background: #000/);
  assert.match(source, /fetch\("\/api\/invitation-layout"/);
  assert.match(source, /rsvpLayoutVariables/);
  assert.match(source, /position: absolute/);
  assert.doesNotMatch(page, /RSVPForm|rsvp-panel/);
  assert.match(source, /scroll-snap-type: y proximity/);
  assert.match(source, /threshold: 0\.01/);
  assert.match(source, /preload="auto"/);
  assert.match(source, /autoPlay = false/);
  assert.match(source, /viewportFit: "cover"/);
  assert.match(source, /title: "Invitez \| Digital Invitation"/);
  assert.match(source, /device-shell/);
  assert.match(source, /device-camera/);
  assert.match(source, /device-home-indicator/);
  assert.match(source, /@media \(min-width: 700px\)/);
  assert.match(source, /window\.addEventListener\("pageshow", onPageShow\)/);
  assert.match(source, /invitez-opening-viewed/);
  assert.match(source, /invitez-rsvp-confirmation/);
  assert.match(source, /CompactRSVPConfirmation/);
  assert.match(source, /className="rsvp-confirmation-card"/);
  assert.match(source, /Your RSVP is in/);
  assert.match(source, /top: calc\(75% - 40px\)/);
  assert.match(source, /font-size: clamp\(1rem, 4\.3vw, 1\.48rem\)/);
  assert.match(source, /font-size: clamp\(0\.78rem, 3\.35vw, 1\.12rem\)/);
  assert.doesNotMatch(source, /rsvp-confirmation-copy small/);
  assert.match(source, /invitation\??\.scrollTo\(\{ top: invitation\.scrollHeight/);
  assert.match(source, /form\.reset\(\)/);
  assert.doesNotMatch(page, /onRSVPEdit|>Edit<|editRSVP/);
  assert.doesNotMatch(source, /setIntroStage\("confirmation"\)/);
  assert.doesNotMatch(source, /confirmation-screen/);

  assert.doesNotMatch(source, /The Night Shift|event-page|gallery|hero|eventDetails|starterPhotos/i);
  assert.doesNotMatch(source, /codex-preview|Your site is taking shape|react-loading-skeleton/i);
});
